### ISSUE TITLE
Post verified source code to EtherScan

### ISSUE THREAD

**Issue by tjayrush** [apbendi/forehash#38]
If you post verified source code to EtherScan people could permissionlessly watch what's happening and create a `forehash explorer`.

**Comment by apbendi** [comment]
Just spent an hour trying to convince EtherScan that my contract code is my contract code. I'll try again tomorrow-- if I don't have any luck, I'm just going to quit computers and go live in the woods.

**Comment by tjayrush** [comment]
Yikes. Just close this idiotic issue. That’s what I would do.

There should be a decentralized way to do that. Why do we have to rely on Etherscan?

-------------------------------
Thomas Jay Rush
TrueBlocks.io
jrush@trueblocks.io
(610) 937-2593

**Comment by apbendi** [comment]
Don't worry I have this feeling about 3x a day 🤣

**Comment by tjayrush** [comment]
Posted. Thanks.
